# Notation {-}

The set of real numbers is denoted by \(\RR\). The set of rational
numbers is denoted by \(\QQ\). The set of integers is denoted by
\(\ZZ\).

The set of \(n\)-tuples with real entries is denoted by
\(\RR^n\). Similar definitions hold for \(\QQ^n\) and
\(\ZZ^n\).

The set of \(m\times n\) matrices (that is, matrices with
\(m\) rows and \(n\) columns) with real entries is denoted \(\RR^{m
\times n}\). Similar definitions hold for \(\QQ^{m\times n}\) and
\(\ZZ^n\).

All \(n\)-tuples are written as columns (that is,
as \(n\times 1\) matrices). An \(n\)-tuple is normally represented by a
lowercase Roman letter in boldface; for example, \(\vec{x}\).
For an \(n\)-tuple \(\vec{x}\), \(x_i\) denotes the \(i\)th entry (or component) of \(\vec{x}\) for \(i = 1,\ldots, n\).

Matrices are normally represented by an uppercase Roman letter in boldface; for example, \(\mm{A}\). The \(j\)th column of a matrix \(\mm{A}\) 
is denoted by \(A_j\) and the \((i,j)\)-entry (that is, the entry in 
row \(i\) and column \(j\)) is denoted by \(a_{ij}\).

Scalars are usually represented by lowercase Greek
letters; for example, \(\lambda\), \(\alpha\), \(\beta\) etc.

An \(n\)-tuple consisting of all zeros is denoted by \(\vec{0}\).
The dimension of the tuple is inferred from the context.

For a matrix \(\mm{A}\), \(\mm{A}^\mathsf{T}\) denotes
the transpose of \(\mathbf{A}\). For an \(n\)-tuple \(\mathbf{x}\),
\(\mathbf{x}^\mathsf{T}\) denotes the transpose of \(\mathbf{x}\).

If \(\mm{A}\) and \(\mm{B}\) are \(m\times n\) matrices,
\(\mm{A} \geq \mm{B}\)
means \(a_{ij} \geq b_{ij}\) for all
\(i = 1,\ldots, m\), \(j = 1,\ldots, n\). Similar definitions hold
for \(\mm{A} \leq \mm{B}\), \(\mm{A} = \mm{B}\),
\(\mm{A} \lt \mm{B}\) and \(\mm{A} \gt \mm{B}\).
In particular, if \(\vec{u}\) and \(\vec{v}\) are \(n\)-tuples,
\(\vec{u}\geq \vec{v}\) means \(u_i \geq v_i\) for 
\(i= 1,\ldots, n\) and \(\vec{u} \gt \vec{0}\) means
\(u_i \gt 0\) for \(i = 1,\ldots,n\).


Superscripts in brackets are used for indexing tuples.
For example, we can write
\(\vec{u}^{(1)},\vec{u}^{(2)} \in \RR^3\). Then
\(\vec{u}^{(1)}\) and \(\vec{u}^{(2)}\) are elements of \(\RR^3\).
The second entry of \(\vec{u}^{(1)}\) is denoted by \(u^{(1)}_2.\)
