## Solutions {-}

1. To infer \(x + y \geq \mu\) from the given system, we need
    \(\alpha \geq 0\), \(\beta \geq 0\), and \(\gamma \geq 0\)
    such that 
    \begin{align*}
      2\alpha + \beta + 3\gamma & = 1\\
       \alpha + 3\beta + 2\gamma & = 1\\
      2\alpha + \beta + 6\gamma & = \mu.
    \end{align*}
    Solving gives \(\begin{bmatrix} \alpha \\ \beta \\ \gamma\end{bmatrix}
    = \begin{bmatrix} \frac{13}{15} - \frac{7}{15} \mu 
    \\ \frac{4}{15}-\frac{1}{15} \mu \\
    -\frac{1}{3} + \frac{1}{3}\mu\end{bmatrix}\).
    The largest value \(\mu\) can take so that this tuple has only
    nonnegative entries is \(\frac{13}{7}\).

2.  We first label the constraints:
    \begin{align}
    2x + y & \geq 2 (\#eq:inf-ex2-1) \\
    x + 5y & \geq 7 (\#eq:inf-ex2-2) \\
    -x + y & = 1.  (\#eq:inf-ex2-3)
    \end{align}
    Let \(C = \left \{ \lambda \begin{bmatrix} 1 \\ 0 \\ 1\end{bmatrix}
    + (1-\lambda)\begin{bmatrix} \frac{1}{3} \\ \frac{1}{3} \\ 0 \end{bmatrix}
    \ssep 0 \leq \lambda \leq 1
    \right\}\).
    Note that \(C\) has infinitely many elements and that
    for every \(\begin{bmatrix} \alpha \\ \beta \\ \gamma\end{bmatrix}
    \in C\), 
    \(\alpha \times\) \@ref(eq:inf-ex2-1) \(+\)
    \(\beta \times\) \@ref(eq:inf-ex2-2) \(+\)
    \(\gamma \times\) \@ref(eq:inf-ex2-3)
    gives the constraint \(x + 2y \geq 3\).
   
    For example, when \(\lambda = \frac{1}{2}\),
    \(\lambda \begin{bmatrix} 1 \\ 0 \\ 1\end{bmatrix}
    + (1-\lambda)\begin{bmatrix} \frac{1}{3} \\ \frac{1}{3} \\ 0 \end{bmatrix}
    = \begin{bmatrix} \frac{2}{3} \\ \frac{1}{6} \\ \frac{1}{2}\end{bmatrix}\).
